# Generated by Django 5.2.6 on 2025-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='hr_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
