# Generated by Django 4.2.1 on 2025-10-01 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_jobapplication_hr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_platform',
            field=models.CharField(blank=True, choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('GLASSDOOR', 'Glassdoor'), ('COMPANY_WEBSITE', 'Company Website'), ('JOBBOARD', 'Job Board'), ('RECRUITER', 'Recruiter Contact'), ('REFERRAL', 'Employee Referral'), ('CAREER_FAIR', 'Career Fair'), ('DIRECT_EMAIL', 'Direct Email'), ('OTHER', 'Other')], help_text='Platform or method used to apply for this job', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='platform_url',
            field=models.URLField(blank=True, help_text='Direct link to job posting if applied online', null=True),
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('PROFESSIONAL', 'Professional'), ('ACADEMIC', 'Academic'), ('OTHER', 'Other')], default='PROFESSIONAL', max_length=20)),
                ('label', models.CharField(help_text="e.g., 'Work Gmail', 'University Email'", max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'email_type', 'label'],
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sender_email',
            field=models.ForeignKey(blank=True, help_text='Email address used to send the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_applications', to='jobs.useremail'),
        ),
    ]
